FROM node:slim AS base

ENV PNPM_HOME=/usr/local/bin

# Build stage
FROM base AS build
WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile || npm install --production
RUN (pnpm install --global @nestjs/cli && pnpm install --save-dev @types/node) \
|| (npm install --global @nestjs/cli && npm install --save-dev @types/node)

COPY . .

RUN npx prisma generate
RUN pnpm run build || npm run build

RUN pnpm prune || npm prune

USER node

# Production stage 
FROM base AS production
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

ENV NODE_ENV=production

COPY --chown=node:node --from=build /app/package.json /app/pnpm-lock.yaml ./
COPY --chown=node:node --from=build /app/node_modules ./node_modules
COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node --from=build /app/prisma ./prisma

CMD ["sh", "-c", "NODE_OPTIONS='--max-old-space-size=2048' node dist/main.js"]

EXPOSE 8000