FROM node:slim AS base

ENV PNPM_HOME=/usr/local/bin
ENV NODE_ENV=development

# Build stage
FROM base AS development
WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install || npm install

COPY . .

RUN npx prisma generate
RUN pnpm prune || npm prune

CMD ["pnpm", "run", "start:dev"]

EXPOSE 8000