import { Routes } from 'src/core/enums/app.enums';

export const RoutesApiTags = {
  [Routes.Users]: 'Users',
  [Routes.Chats]: 'Chats',
  [Routes.Posts]: 'Posts',
  [Routes.ChatMessages]: 'Chat messages',
  [Routes.PostCategories]: 'Post categories',
  [Routes.PostComments]: 'Post comments',
  [Routes.PostDonations]: 'Post donations',
  [Routes.PostReactions]: 'Post reactions',
  [Routes.PostAttachments]: 'Post attachments',
  [Routes.PostReports]: 'Post reports',
  [Routes.PostCommentAttachments]: 'Post comment attachments',
  [Routes.PostCommentReactions]: 'Post comment reactions',
  [Routes.PostCommentReports]: 'Post comment reports',
  [Routes.Followings]: 'Followings',
  [Routes.CategoryToPost]: 'Posts',
  [Routes.ChatToUser]: 'Chats',
  [Routes.ChatRoles]: 'Chat roles',
  [Routes.ChatMessageAttachments]: 'Chat message attachments',
  [Routes.ChatMessageReactions]: 'Chat message reactions',
  [Routes.UserPenalties]: 'User penalties',
  [Routes.UserReports]: 'User reports',
  [Routes.UserRoles]: 'User roles',
  [Routes.Stripe]: 'Stripe',
  [Routes.Utils]: 'Utils',
  [Routes.Auth]: 'Auth',
  [Routes.OAuth2]: 'OAuth2',
  [Routes.Payments]: 'Payments',
};
